apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-grafana
    department: prometheus-grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000