apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: services
spec:
  type: NodePort
  selector:
    app: nginx
    department: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 60000